version: '3.8'

services:
  neo4j:
    image: neo4j:5.12.0  # Use latest stable version
    container_name: neo4j
    restart: always
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_PLUGINS=["apoc","graph-data-science"]
    ports:
      - "7474:7474"   # Neo4j Browser
      - "7687:7687"   # Bolt Protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
