version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"  # S3 API
      - "9090:9090"  # MinIO Console
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
